//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Aquasim.rc
//
#define IDOK2                           2
#define IDC_DEFAULTS                    3
#define IDC_ADD                         3
#define IDC_BU_VARS                     3
#define IDC_BU_ADD                      3
#define IDC_BU_ACT                      3
#define IDC_BU_READ                     3
#define IDC_EDIT                        4
#define IDC_BU_PROCS                    4
#define IDC_BU_INACT                    4
#define IDC_BU_WRITE                    4
#define IDC_BU_ADDBOTTOMBC              4
#define IDC_DELETE                      5
#define IDC_BU_INITS                    5
#define IDC_SCALING                     6
#define IDC_BU_INP                      6
#define IDC_BU_SED                      7
#define IDC_BU_ADD2                     7
#define IDC_BU_TKE                      8
#define IDC_BU_PARTVARS                 9
#define IDC_BU_DISSVARS                 10
#define IDC_BU_ACC                      11
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SYSTEMTYPE                  129
#define IDR_PLOTCURVES                  130
#define IDD_EDITVARIABLES               131
#define IDD_EDIT_VARIABLES              131
#define IDD_EDITPROCESSES               133
#define IDD_EDIT_PROCESSES              133
#define IDD_EDIT_COMPARTMENTS           134
#define IDD_EDIT_LINKS                  135
#define IDD_CALC_SIMULATION             136
#define IDD_CALC_SENSANALYSIS           137
#define IDD_CALC_PARESTIMATION          138
#define IDD_VIEW_RESULTS                139
#define IDD_EDIT_DELSTATES              140
#define IDD_EDIT_SELVARTYPE             141
#define IDD_EDIT_EDSTATEVAR             142
#define IDD_NOTE_L1                     147
#define IDD_NOTE_L2                     148
#define IDD_NOTE_L3                     149
#define IDD_NOTE_S1                     150
#define IDD_NOTE_S2                     151
#define IDD_NOTE_S3                     152
#define IDD_ASK_YES_S1                  155
#define IDD_ASK_NO_S1                   156
#define IDD_ASK_YES_C_S1                158
#define IDD_ASK_NO_C_S1                 159
#define IDD_VIEW_SCREENOPT              161
#define IDD_VIEW_PSOPT                  162
#define IDD_VIEW_LISTOPT                163
#define IDD_VIEW_EDPLOTDEF              164
#define IDD_VIEW_EDCURVEDEF             165
#define IDD_VIEW_EDSCALING              166
#define IDD_WAIT_CANCEL                 170
#define IDD_WAIT_SIM                    171
#define IDD_EDIT_SELCOMPTYPE            172
#define IDD_EDIT_EDLAKECOMP             173
#define IDD_EDIT_COMPLAKE               173
#define IDD_EDIT_EDLAKESED              174
#define IDD_EDIT_COMPLAKESED            174
#define IDD_EDIT_EDLAKETKE              175
#define IDD_EDIT_COMPLAKETKE            175
#define IDD_EDIT_COMPLAKEPARTS          176
#define IDD_EDIT_COMPLAKEPART           177
#define IDD_EDIT_COMPLAKEDISSS          178
#define IDD_EDIT_COMPLAKEDISS           179
#define IDD_EDIT_COMPACTVAR             180
#define IDD_EDIT_COMPACTPROC            181
#define IDD_EDIT_COMPMIX                182
#define IDD_EDIT_COMPMIXINPS            183
#define IDD_EDIT_COMPMIXINP             184
#define IDD_EDIT_COMPMIXINITS           185
#define IDD_EDIT_COMPMIXINIT            186
#define IDD_EDIT_COMPLAKEINITS          187
#define IDD_EDIT_COMPLAKEINIT           188
#define IDD_EDIT_COMPLAKESELINP         189
#define IDD_EDIT_COMPLAKESURFINPS       190
#define IDD_EDIT_COMPLAKESURFINP        191
#define IDD_EDIT_COMPLAKELATINPS        192
#define IDD_EDIT_COMPLAKELATINP         193
#define IDD_EDIT_COMPLAKESEDINPS        194
#define IDD_EDIT_COMPLAKESEDINP         195
#define IDD_EDIT_COMPLAKEPOINTINPS      196
#define IDD_EDIT_COMPLAKEPOINTINP       197
#define IDD_EDIT_COMPLAKEPOINTINPCONC   198
#define IDD_EDIT_VARSTATE               199
#define IDD_EDIT_VARPROG                200
#define IDD_EDIT_VARPAR                 201
#define IDD_EDIT_VARFORM                202
#define IDD_EDIT_VARREALLIST            203
#define IDD_EDIT_VARVARLIST             204
#define IDD_EDIT_VARPROBE               205
#define IDD_EDIT_SELLINKTYPE            206
#define IDD_EDIT_SELPROCTYPE            207
#define IDD_EDIT_PROCDYN                208
#define IDD_EDIT_PROCEQU                209
#define IDD_EDIT_LINKADV                210
#define IDD_EDIT_LINKDIFF               211
#define IDD_EDIT_COMPFILM               212
#define IDD_EDIT_COMPADV                213
#define IDD_EDIT_COMPSOIL               214
#define IDD_EDIT_COMPRIV                215
#define IDD_VIEW_ZOOMING                216
#define IDD_CALC_SENSCALC               220
#define IDD_CALC_CALCDEF                220
#define IDD_WAIT_SENS                   221
#define IDD_WAIT_FIT                    222
#define IDD_CALC_PARESTRES              223
#define IDD_CALC_PARESTCALC             224
#define IDD_CALC_PARESTTARGET           227
#define IDD_EDIT_PROCDYNSTOICH          228
#define IDD_EDIT_VARREALLISTREAD        229
#define IDD_EDIT_NUMPAR                 230
#define IDD_EDIT_LINKADVBIF             231
#define IDD_EDIT_LINKADVBIFFLUX         232
#define IDD_EDIT_LINKDIFFEXCH           233
#define IDD_EDIT_COMPRIVINITS           234
#define IDD_EDIT_COMPRIVINIT            235
#define IDD_EDIT_COMPRIVSELINP          236
#define IDD_EDIT_COMPRIVUPINPS          237
#define IDD_EDIT_COMPRIVUPINP           238
#define IDD_EDIT_COMPRIVLATINPS         239
#define IDD_EDIT_COMPRIVLATINP          240
#define IDD_EDIT_COMPADVINITS           243
#define IDD_EDIT_COMPADVINIT            244
#define IDD_EDIT_COMPADVSELINP          245
#define IDD_EDIT_COMPADVININPS          246
#define IDD_EDIT_COMPADVININP           247
#define IDD_EDIT_COMPADVLATINPS         248
#define IDD_EDIT_COMPADVLATINP          249
#define IDD_EDIT_COMPSOILINITS          250
#define IDD_EDIT_COMPSOILINIT           251
#define IDD_EDIT_COMPSOILSELINP         252
#define IDD_EDIT_COMPSOILININPS         253
#define IDD_EDIT_COMPSOILININP          254
#define IDD_EDIT_COMPSOILLATINPS        255
#define IDD_EDIT_COMPSOILLATINP         256
#define IDD_EDIT_COMPFILMINPS           257
#define IDD_EDIT_COMPFILMINP            258
#define IDD_EDIT_COMPFILMINITS          259
#define IDD_EDIT_COMPFILMINIT           260
#define IDD_EDIT_COMPSOILPARZONE        261
#define IDD_EDIT_COMPSOILSERZONE        262
#define IDD_EDIT_CONVSOILEXCH           263
#define IDD_EDIT_COMPFILMPARTS          264
#define IDD_EDIT_COMPFILMPART           265
#define IDD_EDIT_COMPFILMDISSS          266
#define IDD_EDIT_COMPFILMDISS           267
#define IDD_EDIT_COMPLAKEACC            268
#define IDD_EDIT_COMPMIXACC             269
#define IDD_EDIT_COMPSOILACC            270
#define IDD_EDIT_COMPADVACC             271
#define IDD_EDIT_COMPRIVACC             272
#define IDD_EDIT_COMPFILMACC            273
#define IDD_FILE_PRINTOPT               275
#define IDR_PLOT_TYPE                   277
#define IDD_VIEW_EDSCALINGS             280
#define IDD_EDIT_COMPLAKESEDLAYER       281
#define IDD_EDIT_COMPRIVSED             283
#define IDD_EDIT_COMPRIVSEDLAYER        284
#define IDC_CURSOR1                     285
#define IDD_EDIT_COMPSED                286
#define IDD_EDIT_COMPSEDINITS           287
#define IDD_EDIT_COMPSEDINIT            288
#define IDD_EDIT_COMPSEDINPS            289
#define IDD_EDIT_COMPSEDINP             290
#define IDD_EDIT_COMPSEDTOPBC           290
#define IDD_EDIT_COMPSEDACC             291
#define IDD_EDIT_COMPSEDPARTS           292
#define IDD_EDIT_COMPSEDPART            293
#define IDD_EDIT_COMPSEDDISSS           294
#define IDD_EDIT_COMPSEDDISS            295
#define IDD_EDIT_COMPSEDBOTTOMBC        296
#define IDC_LB_PLOTLIST                 1000
#define IDC_BU_EDITTYPE                 1004
#define IDC_BU_EXCHANGE                 1005
#define IDC_LB_STATELIST                1007
#define IDC_LB_CALCLIST                 1008
#define IDC_BU_DELETECALCS              1009
#define IDC_BU_DELETEINDSTATE           1010
#define IDC_BU_DELETESTATES             1010
#define IDC_BU_INITIALIZE               1011
#define IDC_ED_CALCNUM                  1013
#define IDC_ED_NUMSTEPS                 1014
#define IDC_RB_GIVEN                    1015
#define IDC_RB_STEADY                   1016
#define IDC_ED_STEPSIZE                 1017
#define IDC_ED_INITTIME                 1018
#define IDC_BU_NEWSENS                  1019
#define IDC_BU_EDITSENS                 1020
#define IDC_BU_DUPLSENS                 1020
#define IDC_BU_DELETESENS               1021
#define IDC_BU_ACTSENS                  1022
#define IDC_BU_INACTSENS                1023
#define IDC_BU_EDSENS                   1024
#define IDC_BU_NEWFIT                   1025
#define IDC_BU_EDITFIT                  1026
#define IDC_BU_DELETEFIT                1027
#define IDC_BU_ACTFIT                   1028
#define IDC_BU_INACTFIT                 1029
#define IDC_RB_SECANT                   1030
#define IDC_RB_SIMPLEX                  1031
#define IDC_BU_PLOTTOSCREEN             1033
#define IDC_BU_PLOTTOSCREEN2            1034
#define IDC_BU_PLOTTOFILE               1034
#define IDC_BU_PLOTTOSCREEN3            1035
#define IDC_BU_LISTTOFILE               1035
#define IDC_BU_SCROPT                   1036
#define IDC_BU_FILEOPT                  1037
#define IDC_BU_LISTOPT                  1038
#define IDC_RB_STATEVAR                 1039
#define IDC_RB_PROGVAR                  1040
#define IDC_RB_CONSTVAR                 1041
#define IDC_RB_PARVAR                   1041
#define IDC_RB_REALLISTVAR              1042
#define IDC_RB_VARLISTVAR               1043
#define IDC_RB_FORMVAR                  1044
#define IDC_ED_NAME                     1045
#define IDC_RB_PROBEVAR                 1045
#define IDC_ED_DESCRIPTION              1046
#define IDC_ED_COMPIND                  1046
#define IDC_ED_NAME2                    1046
#define IDC_ED_DESCRIPT                 1047
#define IDC_RB_DYNAMIC                  1048
#define IDC_ED_GRAVIT                   1048
#define IDC_ED_RESUSP                   1048
#define IDC_ED_SEDVELOC                 1048
#define IDC_ED_VOL                      1048
#define IDC_ED_DESCRIPT2                1048
#define IDC_ED_WATERFLOW                1048
#define IDC_ED_VOLREACT                 1048
#define IDC_RB_EQUILIBRIUM              1049
#define IDC_ED_TOP                      1049
#define IDC_ED_PWIND                    1049
#define IDC_ED_OUTFLOW                  1049
#define IDC_ED_EQUATION                 1049
#define IDC_ED_VOLBULK                  1049
#define IDC_ED_VOLATT                   1049
#define IDC_ED_ABSACCQ                  1049
#define IDC_ED_BIOTURB                  1049
#define IDC_ED_MOBILITY                 1049
#define IDC_RB_VOLUME                   1050
#define IDC_ED_BOTTOM                   1050
#define IDC_ED_PINT                     1050
#define IDC_ED_DETACH                   1050
#define IDC_ED_BOUNDRES                 1050
#define IDC_ED_ABSACCN2                 1050
#define IDC_RB_SURFACE                  1051
#define IDC_ED_CROSSSECT                1051
#define IDC_ED_AREA                     1051
#define IDC_ED_MATRIXDIFF               1051
#define IDC_ED_ABSACCU                  1051
#define IDC_ED_RELACC                   1052
#define IDC_ED_DENSITY                  1052
#define IDC_ED_ADVVOLFRACT              1052
#define IDC_ED_RATEPOR                  1052
#define IDC_ED_ABSACCTKE                1052
#define IDC_ED_ABSACC                   1053
#define IDC_ED_DIFFUSION                1053
#define IDC_ED_SURFDET                  1053
#define IDC_ED_ABSACCESEICHE            1053
#define IDC_LB_PROCLIST                 1054
#define IDC_ED_NUMGRID                  1054
#define IDC_ED_MIN                      1054
#define IDC_ED_VOLDET                   1054
#define IDC_ED_ABSACCI                  1054
#define IDC_LB_LINKLIST                 1055
#define IDC_ED_MAX                      1055
#define IDC_ED_POREDIFF                 1055
#define IDC_ED_ISURF                    1055
#define IDC_LB_COMPLIST                 1056
#define IDC_ED_ARGDATA                  1056
#define IDC_ED_ETA                      1056
#define IDC_BU_NEW                      1057
#define IDC_BU_DUPLICATE                1058
#define IDC_BU_EDIT                     1059
#define IDC_ED_WIDTH                    1059
#define IDC_BU_DELETE                   1060
#define IDC_ED_FRICT                    1060
#define IDC_LB_VARLIST                  1061
#define IDC_BU_ADDVAL                   1061
#define IDC_ED_DISP                     1061
#define IDC_BU_EDITBOTTOMBC             1061
#define IDC_LB_ACTPAR                   1062
#define IDC_BU_REPLVAL                  1062
#define IDC_ED_ENDLEVEL                 1062
#define IDC_BU_DELETEBOTTOMBC           1062
#define IDC_LB_AVAILPAR                 1063
#define IDC_BU_ACTPAR                   1064
#define IDC_BU_INACTPAR                 1065
#define IDC_LB_ACTCALC                  1066
#define IDC_LB_AVAILCALC                1067
#define IDC_ED_EDIT1                    1068
#define IDC_ED_MAXIT                    1068
#define IDC_BU_START                    1069
#define IDC_TEXT1                       1073
#define IDC_TEXT2                       1074
#define IDC_TEXT3                       1075
#define IDC_ASK_YES                     1082
#define IDC_ASK_NO                      1083
#define IDC_CANCEL                      1089
#define IDC_WINWIDTH                    1095
#define IDC_MARGINLEFT                  1096
#define IDC_MARGINRIGHT                 1097
#define IDC_LEGWIDTH                    1098
#define IDC_FONTTITLE                   1099
#define IDC_FONTLEGEND                  1100
#define IDC_WINHEIGHT                   1101
#define IDC_MARGINTOP                   1102
#define IDC_MARGINBOTTOM                1103
#define IDC_FONTLABEL                   1104
#define IDC_FONTNUMBERS                 1105
#define IDC_CASCADE                     1106
#define IDC_PAPERSIZE                   1108
#define IDC_DIGITS                      1109
#define IDC_RB_TAB                      1110
#define IDC_RB_Comma                    1111
#define IDC_RB_PORTRAIT                 1111
#define IDC_RB_SPACE                    1112
#define IDC_RB_LANDSCAPE                1112
#define IDC_PLOTCOLUMNS                 1113
#define IDC_PLOTROWS                    1114
#define IDC_RB_COLOR                    1124
#define IDC_RB_BLACKWHITE               1125
#define IDC_RB_CM                       1126
#define IDC_RB_INCH                     1127
#define IDC_NAME                        1128
#define IDC_RB_PTS                      1128
#define IDC_DESCRIPTION                 1129
#define IDC_RB_EPS                      1129
#define IDC_TITLE                       1130
#define IDC_CURVELIST                   1131
#define IDC_RB_ABSCTIME                 1132
#define IDC_RB_ABSCSPACE                1133
#define IDC_ABSCISSALABEL               1134
#define IDC_ORDINATELABEL               1135
#define IDC_RB_VALUE                    1135
#define IDC_RB_ERROR                    1136
#define IDC_RB_SENS                     1137
#define IDC_RB_ABSABS                   1138
#define IDC_RB_RELABS                   1139
#define IDC_RB_ABSREL                   1140
#define IDC_RB_RELREL                   1141
#define IDC_VAR                         1142
#define IDC_PAR                         1143
#define IDC_CALCNUM                     1144
#define IDC_COMP                        1145
#define IDC_ZONE                        1146
#define IDC_TIMESPACE                   1147
#define IDC_LEGEND                      1148
#define IDC_LINEACT                     1149
#define IDC_MARKERCOLOR                 1150
#define IDC_LINEWIDTH                   1151
#define IDC_LINECOLOR                   1152
#define IDC_MARKERACT                   1153
#define IDC_TX_PAR                      1154
#define IDC_MARKERSTYLE                 1155
#define IDC_MARKERSIZE                  1156
#define IDC_LINESTYLE                   1157
#define IDC_TX_ZONE                     1159
#define IDC_TX_COMP                     1160
#define IDC_CB_ABSCMIN                  1161
#define IDC_CB_ABSMAX                   1162
#define IDC_CB_ABSCTPOS                 1163
#define IDC_CB_ABSCTDIST                1164
#define IDC_CB_ORDMIN                   1165
#define IDC_CB_ORDMAX                   1166
#define IDC_CB_ORDTPOS                  1167
#define IDC_CB_ORDTDIST                 1168
#define IDC_ED_ABSCMIN                  1169
#define IDC_ED_ABSCMAX                  1170
#define IDC_WAIT_TIME_TXT               1170
#define IDC_ED_ABSCTPOS                 1171
#define IDC_WAIT_TIME                   1171
#define IDC_ED_ABSCTDIST                1172
#define IDC_RB_MIXEDCOMP                1172
#define IDC_WAIT_BESTCHI                1172
#define IDC_WAIT_CALC_TXT               1172
#define IDC_ED_ORDMIN                   1173
#define IDC_RB_SEDNO                    1173
#define IDC_RB_FILMCOMP                 1173
#define IDC_WAIT_CURCHI                 1173
#define IDC_WAIT_CALC                   1173
#define IDC_ED_ORDMAX                   1174
#define IDC_RB_SEDYES                   1174
#define IDC_RB_ADVCOMP                  1174
#define IDC_ED_ORDTPOS                  1175
#define IDC_RB_TKENO                    1175
#define IDC_RB_SOILCOMP                 1175
#define IDC_ED_ORDTDIST                 1176
#define IDC_RB_TKEYES                   1176
#define IDC_RB_RIVCOMP                  1176
#define IDC_WAIT_TEXT                   1177
#define IDC_RB_LOWRES                   1177
#define IDC_RB_LAKECOMP                 1177
#define IDC_RB_HIGHRES                  1178
#define IDC_ED_POR                      1178
#define IDC_RB_SEDCOMP                  1178
#define IDC_ED_HSED                     1179
#define IDC_ED_VOLFLUX                  1180
#define IDC_ED_DISSIP                   1181
#define IDC_ED_PBOTTOM                  1182
#define IDC_ED_PRANTL                   1183
#define IDC_ED_SURFSHEAR                1184
#define IDC_ED_PRESS                    1185
#define IDC_LB_VARS                     1188
#define IDC_LE_VAR                      1189
#define IDC_ED_SEDEXCH                  1190
#define IDC_LE_ZONE                     1190
#define IDC_LE_COMP                     1190
#define IDC_LE_COMPZONE                 1191
#define IDC_LB_AVAIL                    1193
#define IDC_LB_ACT                      1194
#define IDC_RB_CONSTVOL                 1194
#define IDC_RB_VARVOL                   1195
#define IDC_TX_OUTFLOW                  1196
#define IDC_TX_VOL                      1197
#define IDC_ED_WATINF                   1198
#define IDC_LB_INPUTS                   1199
#define IDC_ED_INPFLUX                  1200
#define IDC_LB_BOTTOMBCS                1200
#define IDC_LB_INITS                    1201
#define IDC_ED_INITCOND                 1202
#define IDC_RB_SURFINP                  1203
#define IDC_ED_CONV1                    1203
#define IDC_ED_EXCHCOEFF                1203
#define IDC_RB_LATINP                   1204
#define IDC_RB_POINTINPS                1205
#define IDC_ED_DEPTH                    1205
#define IDC_RB_SEDINP                   1206
#define IDC_LB_PINPS                    1207
#define IDC_ED_RANGE                    1208
#define IDC_ED_UNIT1                    1211
#define IDC_ED_UNIT                     1211
#define IDC_RB_DYN                      1212
#define IDC_ED_SPACE                    1212
#define IDC_ED_RELSTD                   1212
#define IDC_RB_EQ                       1213
#define IDC_ED_ABSSTD                   1213
#define IDC_RB_VOL                      1214
#define IDC_SURF                        1215
#define IDC_RB_SURF                     1215
#define IDC_ED_UNIT2                    1216
#define IDC_CB_REFTO                    1217
#define IDC_LB_REFTO                    1217
#define IDC_LE_REFTO                    1217
#define IDC_ED_VALUE                    1218
#define IDC_ED_STDEV                    1219
#define IDC_CB_SENSACT                  1220
#define IDC_CB_FITACT                   1221
#define IDC_ED_EXPR                     1221
#define IDC_RB_ADVLINK                  1222
#define IDC_RB_DIFFLINK                 1223
#define IDC_RB_DYNPROC                  1224
#define IDC_RB_EQPROC                   1225
#define IDC_ED_RATE                     1226
#define IDC_LB_STOICH                   1227
#define IDC_ED_LINKIND                  1229
#define IDC_LE_COMPIN                   1230
#define IDC_LE_CONNIN                   1231
#define IDC_LE_COMPOUT                  1232
#define IDC_LE_CONNOUT                  1233
#define IDC_LB_BIFS                     1234
#define IDC_LE_COMP1                    1235
#define IDC_LE_COMP2                    1236
#define IDC_LE_CONN1                    1237
#define IDC_LE_CONN2                    1238
#define IDC_LB_EXCOEFF                  1239
#define IDC_TX_COMPZONE                 1241
#define IDC_CB_STATUS                   1244
#define IDC_WAIT_NUMSIM_TXT             1245
#define IDC_WAIT_NUMSIM                 1246
#define IDC_WAIT_CURSIM_TXT             1247
#define IDC_WAIT_INICHI_TXT             1247
#define IDC_WAIT_CURSIM                 1248
#define IDC_WAIT_BESTCHI_TXT            1248
#define IDC_WAIT_CURCHI_TXT             1249
#define IDC_WAIT_INICHI                 1250
#define IDC_LB_TARGETS                  1251
#define IDC_BU_DUPLFIT                  1252
#define IDC_BU_EDFIT                    1253
#define IDC_TX_STATUS                   1254
#define IDC_TX_NUMITER                  1255
#define IDC_LB_LIST                     1256
#define IDC_TX_CHIINI                   1257
#define IDC_TX_CHIEND                   1258
#define IDC_ED_TORX                     1259
#define IDC_LE_DATA                     1260
#define IDC_TX_DATA                     1261
#define IDC_TX_VAR                      1262
#define IDC_ED_STOICH                   1263
#define IDC_RB_GLOBAL                   1264
#define IDC_RB_INDIVIDUAL               1265
#define IDC_TX_ABSSTD                   1266
#define IDC_TX_RELSTD                   1267
#define IDC_LE_ARG                      1268
#define IDC_LE_VALDATA                  1269
#define IDC_TX_NUMPAIRS                 1270
#define IDC_RB_LINEAR                   1271
#define IDC_RB_SPLINE                   1272
#define IDC_RB_SMOOTH                   1273
#define IDC_CB_ACTIVE                   1274
#define IDC_TX_WIDTH                    1275
#define IDC_ED_VALDATA                  1277
#define IDC_ED_STDDATA                  1278
#define IDC_TX_STDDATA                  1279
#define IDC_TX_START                    1280
#define IDC_ED_START                    1281
#define IDC_ED_END                      1282
#define IDC_TX_END                      1283
#define IDC_CB_DEL                      1284
#define IDC_ED_CODIAG                   1286
#define IDC_TX_CONN1                    1286
#define IDC_ED_MAXSTEP                  1287
#define IDC_TX_CONN2                    1287
#define IDC_ED_ORDER                    1288
#define IDC_TX_COMP1                    1288
#define IDC_TX_COMP2                    1289
#define IDC_ED_FITTOL                   1289
#define IDC_TX_COMPIN                   1290
#define IDC_TX_COMPOUT                  1291
#define IDC_ED_ARG                      1292
#define IDC_TX_CONNIN                   1292
#define IDC_TX_ARG                      1293
#define IDC_TX_CONNOUT                  1293
#define IDC_TX_COMPART                  1294
#define IDC_LE_CONNECT                  1295
#define IDC_RB_WITHWATER                1296
#define IDC_RB_ASGIVEN                  1297
#define IDC_ED_VAL                      1298
#define IDC_TX_FLUXLIST                 1298
#define IDC_TX_VAL                      1299
#define IDC_LB_FLUXES                   1299
#define IDC_ED_STD                      1300
#define IDC_LE_COMPART                  1300
#define IDC_TX_STD                      1301
#define IDC_TX_CONNECT                  1301
#define IDC_ED_FLUX                     1302
#define IDC_ED_EXCH                     1303
#define IDC_ED_PERIMETER                1305
#define IDC_RB_WITHOUTDISP              1306
#define IDC_RB_WITHDISP                 1307
#define IDC_RB_METHKIN                  1308
#define IDC_RB_METHDIFF                 1309
#define IDC_RB_LEVNORM                  1310
#define IDC_RB_LEVCRIT                  1311
#define IDC_TX_ENDLEVEL                 1312
#define IDC_RB_LEVGIVEN                 1313
#define IDC_RB_UPSTREAMINP              1313
#define IDC_RB_INLETINP                 1314
#define IDC_RB_WITHOUTDIFF              1315
#define IDC_RB_WITHDIFF                 1316
#define IDC_ED_DIFF                     1317
#define IDC_RB_MATRIXRIGID              1317
#define IDC_LB_PARZONES                 1318
#define IDC_RB_MATRIXDIFF               1318
#define IDC_ED_ZONEIND                  1319
#define IDC_RB_DETACHINDI               1319
#define IDC_ED_VOLFRACT                 1320
#define IDC_RB_DETACHGLOB               1320
#define IDC_LB_EXCHPARS                 1321
#define IDC_ED_POROSITY                 1321
#define IDC_TX_EXCHLIST                 1322
#define IDC_TX_EXCHCOEFF                1323
#define IDC_ED_CONVFACT                 1324
#define IDC_LB_SERZONES                 1325
#define IDC_TX_VOLREACT                 1326
#define IDC_TX_VOLBULK                  1327
#define IDC_RB_CONFINED                 1328
#define IDC_RB_UNCONFINED               1329
#define IDC_RB_PORELIQ                  1330
#define IDC_RB_POREPART                 1331
#define IDC_ED_SURFATT                  1332
#define IDC_TX_VERSION                  1333
#define IDC_ED_RELACCQ                  1334
#define IDC_ED_RELACCN2                 1335
#define IDC_ED_RELACCU                  1336
#define IDC_ED_RELACCV                  1336
#define IDC_ED_RELACCTKE                1337
#define IDC_ED_ABSACCV                  1337
#define IDC_ED_RELACCESEICHE            1338
#define IDC_ED_RELACCD                  1338
#define IDC_ED_ABSACCD                  1339
#define IDC_ED_RELACCI                  1339
#define IDC_ED_RELACCA                  1340
#define IDC_ED_ABSACCA                  1341
#define IDC_ED_RELACCZ                  1342
#define IDC_ED_ABSACCZ                  1343
#define IDC_ED_RELACCE                  1344
#define IDC_ED_ABSACCE                  1345
#define IDC_ED_RELACCEPS                1348
#define IDC_ED_ABSACCEPS                1349
#define IDC_RB_LONG                     1350
#define IDC_RB_SHORT                    1351
#define IDC_TX_TYPE                     1352
#define IDC_BU_REPLACE                  1355
#define IDC_BU_ACTCALC                  1357
#define IDC_BU_INACTCALC                1358
#define IDC_CB_SENSSTATUS               1359
#define IDC_CB_SIMSTATUS                1360
#define IDC_ED_SIGTKE                   1360
#define IDC_ED_SIGEPS                   1361
#define IDC_TX_STATES                   1361
#define IDC_LB_SEDLAYERS                1362
#define IDC_ED_KZMIN                    1362
#define IDC_ED_THICKNESS                1363
#define IDC_ED_VELOCITY                 1364
#define IDC_ED_DISPERSION               1365
#define IDC_CB_SPACEREL                 1370
#define IDC_ED_RELACCPOR                1373
#define IDC_ED_ABSACCPOR                1374
#define IDC_ED_INPCONC                  1375
#define IDC_ED_CONC                     1375
#define IDC_ED_SURFPOR                  1376
#define IDC_LB_TOPBCS                   1377
#define IDC_BU_ADDTOPBC                 1378
#define IDC_BU_EDITTOPBC                1379
#define IDC_BU_DELETETOPBC              1380
#define ID_EDIT_VARIABLES               32771
#define ID_EDIT_PROCESSES               32772
#define ID_EDIT_COMPARTMENTS            32773
#define ID_EDIT_LINKS                   32774
#define ID_EDIT_NUMERICALPARAMETERS     32775
#define ID_EDIT_DELETESTATES            32776
#define ID_CALC_SIMULATION              32777
#define ID_CALC_SENSITIVITYANALYSIS     32778
#define ID_CALC_PARAMETERESTIMATION     32779
#define ID_VIEW_RESULTS                 32780
#define ID_EDIT_SYSTEM                  32781
#define ID_VIEW_CLOSEDIALOGS            32782
#define ID_FILE_REVERT                  32783
#define ID_FILE_ABOUT                   32784
#define ID_FILE_PRINT_AQUA              32785
#define ID_FILE_NEW_AQUA                32786
#define ID_FILE_OPEN_AQUA               32787
#define ID_FILE_CLOSE_AQUA              32788
#define ID_FILE_SAVE_AQUA               32789
#define ID_FILE_SAVE_AS_AQUA            32790
#define ID_VIEW_COORDINATES             32791
#define ID_VIEW_DISPLAYOPTIONS_COORDINATENUMBERS 32792
#define ID_VIEW_DISPLAYOPTIONS_CROSSCURSOR 32793
#define ID_VIEW_DISPLAYOPTIONS_LINECURSOR 32794
#define ID_VIEW_ZOOMING                 32795
#define ID_VIEW_CLOSEPLOTS              32796
#define ID_FILE_PRINTOPT                32797
#define ID_PLOT_COPY                    32798
#define ID_PLOT_PRINT                   32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        297
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1382
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
